import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { PageHeaderComponent } from '../../shared/ui/page-header.component';
import { NotifyService, errMsg } from '../../shared/ui/notify.service';
import { environment } from '../../../environments/environment';

type Overview = { invoiceCount:number; invoicedAmount:number; collectedAmount:number; pendingPaymentRequests:number; activeSubscriptions:number; expiredSubscriptions:number };
type Catalog = { gyms:number; members:number; plans:number; features:number; subscriptions:number; invoices:number; payments:number; auditEntries:number; jobRuns:number; outboxMessages:number };
@Component({ selector:'app-reports', standalone:true, changeDetection:ChangeDetectionStrategy.OnPush, imports:[CommonModule,PageHeaderComponent], template:`
  <div class="lf-page"><app-page-header title="مركز التقارير" subtitle="تقارير تشغيلية ومالية قابلة للطباعة والتصدير" icon="pi pi-chart-line"><button class="lf-btn lf-btn-secondary" (click)="print()"><i class="pi pi-print"></i> طباعة</button><button class="lf-btn lf-btn-primary" (click)="exportCsv()"><i class="pi pi-download"></i> CSV</button></app-page-header>
    <section class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">@for (item of reportLinks; track item.route) {<a [href]="item.route" class="lf-card report-card p-5"><span class="report-icon" [class]="item.tone"><i [class]="item.icon"></i></span><div><h2>{{item.title}}</h2><p>{{item.description}}</p></div><i class="pi pi-arrow-left mr-auto text-slate-400"></i></a>}</section>
    @if (data(); as d) {<section class="lf-card p-5"><div class="lf-section-heading"><div><h2>ملخص مالي وتشغيلي</h2><p>بيانات التقرير الحالي من الباك اند</p></div><span class="lf-chip">محدّث الآن</span></div><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6"><div class="lf-stat"><b>{{d.invoiceCount|number}}</b><span>الفواتير</span></div><div class="lf-stat"><b>{{d.invoicedAmount|number:'1.0-2'}}</b><span>قيمة الفواتير</span></div><div class="lf-stat"><b class="text-emerald-600">{{d.collectedAmount|number:'1.0-2'}}</b><span>المحصّل</span></div><div class="lf-stat"><b class="text-amber-600">{{d.pendingPaymentRequests|number}}</b><span>دفعات معلقة</span></div><div class="lf-stat"><b class="text-indigo-600">{{d.activeSubscriptions|number}}</b><span>نشطة</span></div><div class="lf-stat"><b class="text-rose-600">{{d.expiredSubscriptions|number}}</b><span>منتهية</span></div></div></section>}
    @if (catalog(); as c) {<section class="lf-card p-5"><div class="lf-section-heading"><div><h2>كتالوج بيانات النظام</h2><p>إجمالي السجلات المتاحة لكل مجال</p></div><span class="lf-chip">تدقيق شامل</span></div><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">@for (item of catalogItems(c); track item.label) {<div class="lf-stat"><b>{{item.value|number}}</b><span>{{item.label}}</span></div>}</div></section>}
    @else if (!loading()) {<div class="lf-empty-state"><i class="pi pi-chart-line"></i><h3>لا تتوفر بيانات التقرير</h3></div>}
  </div>` })
export class ReportsComponent implements OnInit {
  private http=inject(HttpClient); private notify=inject(NotifyService); data=signal<Overview|null>(null); catalog=signal<Catalog|null>(null); loading=signal(true);
  reportLinks=[{title:'الجيمات والاشتراكات',description:'الحالات والخطط والتجديدات والإلغاءات',route:'/tenants',icon:'pi pi-building',tone:'bg-indigo-50 text-indigo-600'},{title:'المدفوعات والفواتير',description:'الفواتير والمدفوعات والتحصيل',route:'/invoices',icon:'pi pi-file',tone:'bg-emerald-50 text-emerald-600'},{title:'المميزات والحدود',description:'الميزات والـOverrides والـQuotas',route:'/features',icon:'pi pi-star',tone:'bg-amber-50 text-amber-600'},{title:'الأعضاء والاستخدام',description:'الاستخدام والحدود حسب الجيم',route:'/subscriptions',icon:'pi pi-users',tone:'bg-sky-50 text-sky-600'},{title:'النسخ والوظائف',description:'النسخ الاحتياطية والـJobs والـOutbox',route:'/operations',icon:'pi pi-cog',tone:'bg-violet-50 text-violet-600'},{title:'التدقيق والصلاحيات',description:'سجل التدقيق والمديرون والأدوار',route:'/audit-logs',icon:'pi pi-shield',tone:'bg-rose-50 text-rose-600'}];
  ngOnInit(){this.http.get<Overview>(`${environment.apiUrl}/reports/overview`).subscribe({next:x=>{this.data.set(x);this.loading.set(false)},error:e=>{this.notify.error(errMsg(e));this.loading.set(false)}});this.http.get<Catalog>(`${environment.apiUrl}/reports/catalog`).subscribe({next:x=>this.catalog.set(x)});}
  print(){window.print()}
  catalogItems(c: Catalog){return [{label:'الجيمات',value:c.gyms},{label:'الأعضاء',value:c.members},{label:'الباقات',value:c.plans},{label:'المميزات',value:c.features},{label:'الاشتراكات',value:c.subscriptions},{label:'الفواتير',value:c.invoices},{label:'المدفوعات',value:c.payments},{label:'سجل التدقيق',value:c.auditEntries},{label:'تشغيل Jobs',value:c.jobRuns},{label:'رسائل Outbox',value:c.outboxMessages}];}
  exportCsv(){const d=this.data();const c=this.catalog();if(!d)return;const rows=[['المؤشر','القيمة'],['عدد الفواتير',d.invoiceCount],['قيمة الفواتير',d.invoicedAmount],['المحصّل',d.collectedAmount],['طلبات دفع معلقة',d.pendingPaymentRequests],['اشتراكات نشطة',d.activeSubscriptions],['اشتراكات منتهية',d.expiredSubscriptions],...(c?[['الجيمات',c.gyms],['الأعضاء',c.members],['الباقات',c.plans],['المميزات',c.features],['المدفوعات',c.payments],['سجل التدقيق',c.auditEntries]]:[])];const csv='\\uFEFF'+rows.map(r=>r.join(',')).join('\\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`logicfit-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
}
