import { Component, ChangeDetectionStrategy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { PageHeaderComponent } from '../../shared/ui/page-header.component';
import { NotifyService, errMsg } from '../../shared/ui/notify.service';
import { environment } from '../../../environments/environment';
@Component({selector:'app-operations',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[CommonModule,TableModule,ButtonModule,PageHeaderComponent],template:`<div class="lf-page"><div class="lf-toolbar"><app-page-header title="مراقبة العمليات" subtitle="متابعة الـJobs ورسائل Outbox وحالات الفشل" icon="pi pi-cog"></app-page-header><button pButton label="تحديث" icon="pi pi-refresh" (click)="load()"></button></div><div class="grid grid-cols-1 xl:grid-cols-2 gap-4"><div class="lf-table-shell"><h3 class="p-4 m-0 lf-section-title">سجل تنفيذ المهام</h3><p-table [value]="jobs()" [loading]="loading()"><ng-template pTemplate="header"><tr><th>المهمة</th><th>الحالة</th><th>وقت البدء</th><th>المحاولات</th></tr></ng-template><ng-template pTemplate="body" let-x><tr><td>{{x.jobName}}</td><td>{{x.status}}</td><td>{{x.startedAtUtc | date:'medium'}}</td><td>{{x.attemptCount}}</td></tr></ng-template></p-table></div><div class="lf-table-shell"><h3 class="p-4 m-0 lf-section-title">رسائل Outbox</h3><p-table [value]="outbox()" [loading]="loading()"><ng-template pTemplate="header"><tr><th>النوع</th><th>وقت الإنشاء</th><th>تمت المعالجة</th><th>المحاولات</th></tr></ng-template><ng-template pTemplate="body" let-x><tr><td>{{x.type}}</td><td>{{x.occurredAtUtc | date:'medium'}}</td><td>{{x.processedAtUtc ? 'نعم' : 'لا'}}</td><td>{{x.attemptCount}}</td></tr></ng-template></p-table></div></div></div>`})
export class OperationsComponent {private http=inject(HttpClient);private notify=inject(NotifyService);jobs=signal<any[]>([]);outbox=signal<any[]>([]);loading=signal(false);ngOnInit(){this.load()}load(){this.loading.set(true);this.http.get<any[]>(`${environment.apiUrl}/operations/jobs`).subscribe({next:x=>{this.jobs.set(x);this.http.get<any[]>(`${environment.apiUrl}/operations/outbox`).subscribe({next:y=>{this.outbox.set(y);this.loading.set(false)},error:e=>this.fail(e)})},error:e=>this.fail(e)})}private fail(e:any){this.notify.error(errMsg(e));this.loading.set(false)}}
