import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FeaturesService } from '../features/features.service';
import { TenantsService } from '../tenants/tenants.service';
import { FeatureDto, PlatformTenantDto } from '../../core/models/platform.models';
import { FormsModule } from '@angular/forms';

@Component({selector:'app-feature-overrides',standalone:true,imports:[CommonModule,FormsModule],template:`<div class="p-6"><h1 class="text-2xl font-bold">Feature Overrides</h1><p class="text-slate-500">فتح أو إغلاق ميزة لجيم محدد مع سبب ومدة.</p><div class="lf-card mt-5 p-4 grid gap-3 md:grid-cols-4"><select class="lf-input" [(ngModel)]="tenantId"><option value="">Tenant</option><option *ngFor="let t of tenants()" [value]="t.id">{{t.name}}</option></select><select class="lf-input" [(ngModel)]="featureId"><option value="">Feature</option><option *ngFor="let f of features()" [value]="f.id">{{f.code}}</option></select><select class="lf-input" [(ngModel)]="isEnabled"><option [ngValue]="true">Enabled</option><option [ngValue]="false">Disabled</option></select><input class="lf-input" [(ngModel)]="reason" placeholder="Reason"/><input class="lf-input" type="datetime-local" [(ngModel)]="endsAt"/><button class="lf-btn lf-btn-primary" (click)="save()">Save Override</button></div><div class="lf-card mt-5 overflow-auto"><table class="w-full text-sm"><thead><tr><th class="p-3 text-start">Tenant</th><th class="p-3 text-start">Feature</th><th class="p-3 text-start">Status</th><th class="p-3 text-start">Reason</th></tr></thead><tbody><tr *ngFor="let o of rows()" class="border-t"><td class="p-3">{{o.tenantId}}</td><td class="p-3">{{o.featureCode}}</td><td class="p-3">{{o.isEnabled ? 'Enabled' : 'Disabled'}}</td><td class="p-3">{{o.reason}}</td></tr></tbody></table></div></div>`})
export class FeatureOverridesComponent implements OnInit { private service=inject(FeaturesService); private tenantsService=inject(TenantsService); rows=signal<any[]>([]); features=signal<FeatureDto[]>([]); tenants=signal<PlatformTenantDto[]>([]); tenantId=''; featureId=''; isEnabled=true; reason=''; endsAt=''; ngOnInit(){this.service.overrides().subscribe(x=>this.rows.set(x));this.service.list().subscribe(x=>this.features.set(x));this.tenantsService.list().subscribe(x=>this.tenants.set(x));} save(){if(!this.tenantId||!this.featureId||!this.reason.trim())return;this.service.setOverride({tenantId:this.tenantId,featureId:this.featureId,isEnabled:this.isEnabled,reason:this.reason,startsAt:new Date().toISOString(),endsAt:this.endsAt?new Date(this.endsAt).toISOString():null}).subscribe(()=>this.service.overrides().subscribe(x=>this.rows.set(x)));} }
