import { Component, ChangeDetectionStrategy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { PageHeaderComponent } from '../../shared/ui/page-header.component';
import { NotifyService, errMsg } from '../../shared/ui/notify.service';
import { environment } from '../../../environments/environment';

@Component({selector:'app-roles',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[CommonModule,TableModule,ButtonModule,PageHeaderComponent],template:`<div class="lf-page"><app-page-header title="الأدوار والصلاحيات" subtitle="إدارة صلاحيات أدوار المنصة" icon="pi pi-shield"></app-page-header><div class="grid grid-cols-1 xl:grid-cols-2 gap-4"><div class="lf-table-shell"><p-table [value]="roles()" [loading]="loading()"><ng-template pTemplate="header"><tr><th>الدور</th><th>الصلاحيات</th><th></th></tr></ng-template><ng-template pTemplate="body" let-row><tr><td><b>{{row.name}}</b></td><td>{{row.permissions?.length||0}}</td><td><button pButton label="تعديل" [text]="true" (click)="select(row)"></button></td></tr></ng-template></p-table></div>@if(selected();as role){<div class="lf-card p-5"><div class="lf-toolbar"><div><h3 class="lf-section-title">صلاحيات {{role.name}}</h3><p class="lf-section-subtitle">لا يمكن تعديل دور مالك المنصة</p></div><button pButton label="حفظ" icon="pi pi-save" [loading]="saving()" (click)="save()"></button></div><div class="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-4 max-h-[520px] overflow-auto">@for(p of catalog();track p.code){<label class="flex items-center gap-2 p-2 rounded-lg hover:bg-slate-50 cursor-pointer"><input type="checkbox" [checked]="has(p.code)" (change)="toggle(p.code)"/><span class="text-sm">{{p.displayName||p.code}}</span></label>}</div></div>}</div></div>`})
export class RolesComponent {private http=inject(HttpClient);private notify=inject(NotifyService);roles=signal<any[]>([]);catalog=signal<any[]>([]);selected=signal<any|null>(null);chosen=signal<Set<string>>(new Set());loading=signal(false);saving=signal(false);ngOnInit(){this.load()}load(){this.loading.set(true);this.http.get<any[]>(`${environment.apiUrl}/roles`).subscribe({next:r=>{this.roles.set(r);this.http.get<any[]>(`${environment.apiUrl}/roles/permissions`).subscribe({next:p=>{this.catalog.set(p);this.loading.set(false)},error:e=>this.fail(e)})},error:e=>this.fail(e)})}select(role:any){this.selected.set(role);this.chosen.set(new Set(role.permissions||[]))}has(code:string){return this.chosen().has(code)}toggle(code:string){const x=new Set(this.chosen());x.has(code)?x.delete(code):x.add(code);this.chosen.set(x)}save(){const role=this.selected();if(!role)return;this.saving.set(true);this.http.put(`${environment.apiUrl}/roles/${role.id}/permissions`,{permissionCodes:[...this.chosen()]}).subscribe({next:()=>{this.saving.set(false);this.notify.success('تم حفظ الصلاحيات');this.load()},error:e=>{this.saving.set(false);this.notify.error(errMsg(e))}})}private fail(e:any){this.notify.error(errMsg(e));this.loading.set(false)}}
