import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { PageHeaderComponent } from '../../shared/ui/page-header.component';
import { DashboardService } from './dashboard.service';
import { PlatformDashboardDto } from '../../core/models/platform.models';
import { NotifyService, errMsg } from '../../shared/ui/notify.service';

type Kpi = { label: string; value: number; icon: string; tone: string };

@Component({ selector: 'app-dashboard', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, imports: [CommonModule, FormsModule, RouterLink, PageHeaderComponent], template: `
  <div class="lf-page">
    <div class="lf-toolbar"><app-page-header title="لوحة قيادة المنصة" subtitle="رؤية تشغيلية ومالية شاملة لكل الجيمات والاشتراكات" icon="pi pi-sparkles"></app-page-header><div class="flex flex-wrap gap-2"><select class="lf-input !w-auto" [(ngModel)]="status" (ngModelChange)="load()"><option [ngValue]="null">كل الحالات</option><option [ngValue]="3">نشط</option><option [ngValue]="2">تجريبي</option><option [ngValue]="7">منتهي</option><option [ngValue]="5">موقوف</option></select><button class="lf-btn lf-btn-secondary" (click)="load()"><i class="pi pi-refresh"></i> تحديث</button></div></div>
    @if (loading()) { <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">@for (item of skeleton; track item) {<div class="lf-card h-32 animate-pulse bg-slate-50"></div>}</div> }
    @else if (error()) { <div class="lf-empty-state"><i class="pi pi-exclamation-triangle"></i><h3>تعذر تحميل مؤشرات المنصة</h3><p>{{ error() }}</p><button class="lf-btn lf-btn-primary mt-3" (click)="load()">إعادة المحاولة</button></div> }
    @else { @if (data(); as dashboard) {
      @if (dashboard.pendingApprovalGyms > 0 || dashboard.suspendedGyms > 0 || dashboard.failedJobs > 0) {<a routerLink="/alerts" class="lf-alert-banner"><span class="lf-alert-icon"><i class="pi pi-bell"></i></span><span><b>توجد إجراءات تحتاج متابعة.</b> {{ dashboard.pendingApprovalGyms }} موافقة معلقة، {{ dashboard.suspendedGyms }} موقوفة، {{ dashboard.failedJobs }} مهمة فاشلة.</span><i class="pi pi-arrow-left mr-auto"></i></a>}
      <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">@for (item of kpis(dashboard); track item.label) {<article class="lf-card lf-kpi-card"><div class="lf-kpi-icon" [ngClass]="item.tone"><i [class]="item.icon"></i></div><div><div class="lf-kpi-value">{{ item.value | number }}</div><div class="lf-kpi-label">{{ item.label }}</div></div></article>}</div>
      <div class="grid grid-cols-1 gap-4 xl:grid-cols-3"><section class="lf-card p-6 xl:col-span-2"><div class="lf-section-heading"><div><h2>صحة المنصة</h2><p>توزيع الجيمات حسب الحالة الحالية</p></div><span class="lf-chip">مباشر</span></div><div class="mt-7 space-y-5">@for (row of health(dashboard); track row.label) {<div><div class="mb-2 flex items-center justify-between text-sm"><span class="font-semibold text-slate-700">{{ row.label }}</span><span class="font-bold text-slate-900">{{ row.value }}%</span></div><div class="lf-progress"><span [ngClass]="row.tone" [style.width.%]="row.value"></span></div></div>}</div></section><section class="lf-card p-6"><div class="lf-section-heading"><div><h2>إجراءات سريعة</h2><p>انتقل مباشرة إلى المهام الأكثر أهمية</p></div></div><div class="mt-5 grid gap-2"><a routerLink="/tenants" class="lf-quick-link"><i class="pi pi-building"></i> إدارة الجيمات <i class="pi pi-angle-left mr-auto"></i></a><a routerLink="/payment-requests" class="lf-quick-link"><i class="pi pi-wallet"></i> مراجعة المدفوعات <i class="pi pi-angle-left mr-auto"></i></a><a routerLink="/alerts" class="lf-quick-link"><i class="pi pi-bell"></i> مركز الإشعارات <i class="pi pi-angle-left mr-auto"></i></a><a routerLink="/operations" class="lf-quick-link"><i class="pi pi-cog"></i> مراقبة العمليات <i class="pi pi-angle-left mr-auto"></i></a></div></section></div>
      <div class="grid grid-cols-1 gap-4 lg:grid-cols-3"><section class="lf-card p-6 lg:col-span-2"><div class="lf-section-heading"><div><h2>المؤشرات المالية</h2><p>الفواتير والمدفوعات والتحصيل</p></div><span class="lf-chip">{{ dashboard.collectedAmount | number:'1.0-2' }} EGP محصل</span></div><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div class="rounded-xl bg-slate-50 p-3"><b class="block text-xl">{{ dashboard.invoiceCount | number }}</b><span class="text-xs text-slate-500">الفواتير</span></div><div class="rounded-xl bg-emerald-50 p-3"><b class="block text-xl text-emerald-700">{{ dashboard.collectedAmount | number:'1.0-2' }}</b><span class="text-xs text-slate-500">المحصّل</span></div><div class="rounded-xl bg-amber-50 p-3"><b class="block text-xl text-amber-700">{{ dashboard.pendingPayments | number }}</b><span class="text-xs text-slate-500">دفعات معلقة</span></div><div class="rounded-xl bg-indigo-50 p-3"><b class="block text-xl text-indigo-700">{{ dashboard.activeSubscriptions | number }}</b><span class="text-xs text-slate-500">اشتراكات نشطة</span></div></div></section><section class="lf-card p-6"><div class="lf-section-heading"><div><h2>سلامة التشغيل</h2><p>العناصر التي تحتاج تدخلاً</p></div></div><div class="mt-5 space-y-3"><a routerLink="/operations" class="lf-quick-link"><i class="pi pi-cog"></i><span>مهام فاشلة</span><b class="mr-auto text-rose-600">{{ dashboard.failedJobs | number }}</b></a><a routerLink="/operations" class="lf-quick-link"><i class="pi pi-send"></i><span>Outbox متعطل</span><b class="mr-auto text-rose-600">{{ dashboard.failedOutbox | number }}</b></a><a routerLink="/features" class="lf-quick-link"><i class="pi pi-star"></i><span>المميزات والحدود</span><b class="mr-auto text-indigo-600">{{ dashboard.featureCount | number }} / {{ dashboard.quotaDefinitionCount | number }}</b></a></div></section></div>
      <section class="lf-card overflow-hidden p-5"><div class="lf-section-heading"><div><h2>تفاصيل الجيمات</h2><p>Drill-down سريع للحالة والاشتراك والاستخدام</p></div><a routerLink="/tenants" class="lf-btn lf-btn-secondary">إدارة الكل <i class="pi pi-arrow-left"></i></a></div><div class="mt-4 overflow-x-auto"><table class="min-w-full text-right text-sm"><thead><tr class="border-b border-slate-100 text-xs text-slate-500"><th class="p-3">الجيم</th><th class="p-3">الحالة</th><th class="p-3">الخطة</th><th class="p-3">الأعضاء</th><th class="p-3">الانتهاء</th></tr></thead><tbody>@for (tenant of tenants(); track tenant.id) {<tr class="border-b border-slate-50"><td class="p-3 font-bold">{{ tenant.name }}<span class="block text-xs font-normal text-slate-400">{{ tenant.subdomain || 'بدون نطاق' }}</span></td><td class="p-3"><span class="lf-badge lf-badge-blue">{{ tenant.status }}</span></td><td class="p-3">{{ tenant.subscription?.planName || 'غير مشترك' }}</td><td class="p-3">{{ tenant.membersCount | number }}</td><td class="p-3">{{ tenant.subscription?.endDate ? (tenant.subscription.endDate | date:'shortDate') : '—' }}</td></tr>} @empty {<tr><td colspan="5" class="p-6 text-center text-slate-400">لا توجد جيمات مطابقة</td></tr>}</tbody></table></div></section>
    } @else { <div class="lf-empty-state"><i class="pi pi-chart-bar"></i><h3>لا تتوفر بيانات للعرض حاليًا</h3></div> } }
  </div>` })
export class DashboardComponent implements OnInit {
  private service = inject(DashboardService); private notify = inject(NotifyService);
  readonly skeleton = [1,2,3,4,5,6,7,8]; loading = signal(true); error = signal(''); data = signal<PlatformDashboardDto | null>(null); tenants = signal<any[]>([]); status: number | null = null;
  ngOnInit(): void { this.load(); this.service.getTenants().subscribe({ next: response => this.tenants.set(response.items ?? []), error: () => this.tenants.set([]) }); }
  load(): void { this.loading.set(true); this.error.set(''); this.service.get({ subscriptionStatus: this.status ?? undefined }).subscribe({ next: value => { this.data.set(value); this.loading.set(false); }, error: error => { const message = errMsg(error); this.error.set(message); this.notify.error(message); this.loading.set(false); } }); }
  kpis(value: PlatformDashboardDto): Kpi[] { return [
    { label: 'إجمالي الجيمات', value: value.totalGyms, icon: 'pi pi-building', tone: 'lf-tone-indigo' }, { label: 'جيمات نشطة', value: value.activeGyms, icon: 'pi pi-check-circle', tone: 'lf-tone-emerald' }, { label: 'فترة تجريبية', value: value.trialGyms, icon: 'pi pi-clock', tone: 'lf-tone-sky' }, { label: 'بانتظار الموافقة', value: value.pendingApprovalGyms, icon: 'pi pi-hourglass', tone: 'lf-tone-amber' }, { label: 'جيمات موقوفة', value: value.suspendedGyms, icon: 'pi pi-ban', tone: 'lf-tone-rose' }, { label: 'إجمالي الأعضاء', value: value.totalMembers, icon: 'pi pi-users', tone: 'lf-tone-violet' }, { label: 'اشتراكات منتهية', value: value.expiredSubscriptions, icon: 'pi pi-calendar-times', tone: 'lf-tone-rose' }, { label: 'المميزات المتاحة', value: value.featureCount, icon: 'pi pi-star', tone: 'lf-tone-indigo' }
  ]; }
  health(value: PlatformDashboardDto) { const total = Math.max(value.totalGyms, 1); return [{ label: 'النشاط', value: Math.round(value.activeGyms * 100 / total), tone: 'bg-emerald-500' }, { label: 'الفترة التجريبية', value: Math.round(value.trialGyms * 100 / total), tone: 'bg-sky-500' }, { label: 'تحتاج متابعة', value: Math.round((value.pendingApprovalGyms + value.suspendedGyms) * 100 / total), tone: 'bg-amber-500' }]; }
}
