import { Component, ChangeDetectionStrategy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { PageHeaderComponent } from '../../shared/ui/page-header.component';
import { NotifyService, errMsg } from '../../shared/ui/notify.service';
import { environment } from '../../../environments/environment';

@Component({selector:'app-administrators',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[CommonModule,FormsModule,TableModule,ButtonModule,PageHeaderComponent],template:`
<div class="lf-page"><app-page-header title="مشرفو المنصة" subtitle="إدارة حسابات فريق إدارة المنصة" icon="pi pi-users"></app-page-header>
<div class="lf-card p-4"><h3 class="lf-section-title mb-4">إضافة مشرف منصة</h3><div class="grid grid-cols-1 md:grid-cols-4 gap-3 items-end"><div><label class="lf-label">الاسم الكامل</label><input class="lf-input" [(ngModel)]="fullName"/></div><div><label class="lf-label">البريد الإلكتروني</label><input class="lf-input" type="email" [(ngModel)]="email"/></div><div><label class="lf-label">كلمة المرور</label><input class="lf-input" type="password" [(ngModel)]="password" placeholder="12 حرفًا على الأقل"/></div><button pButton label="إنشاء مشرف" icon="pi pi-user-plus" [loading]="creating()" (click)="create()"></button></div></div>
<div class="lf-table-shell"><p-table [value]="rows()" [loading]="loading()"><ng-template pTemplate="header"><tr><th>الاسم</th><th>البريد</th><th>الدور</th><th>الحالة</th><th>إجراء</th></tr></ng-template><ng-template pTemplate="body" let-row><tr><td>{{row.fullName||'—'}}</td><td>{{row.email}}</td><td>{{row.role}}</td><td><span class="lf-badge" [class.lf-badge-green]="row.isActive" [class.lf-badge-red]="!row.isActive">{{row.isActive?'نشط':'موقوف'}}</span></td><td><button pButton [label]="row.isActive?'تعطيل':'تفعيل'" [severity]="row.isActive?'danger':'success'" [text]="true" (click)="toggle(row)"></button></td></tr></ng-template><ng-template pTemplate="emptymessage"><tr><td colspan="5" class="text-center py-8">لا يوجد مشرفون</td></tr></ng-template></p-table></div></div>`})
export class AdministratorsComponent { private http=inject(HttpClient); private notify=inject(NotifyService); rows=signal<any[]>([]); loading=signal(false); creating=signal(false); fullName='';email='';password='';ngOnInit(){this.load()} load(){this.loading.set(true);this.http.get<any[]>(`${environment.apiUrl}/administrators`).subscribe({next:r=>{this.rows.set(r);this.loading.set(false)},error:e=>{this.notify.error(errMsg(e));this.loading.set(false)}})} create(){if(!this.fullName||!this.email||this.password.length<12){this.notify.error('أدخل الاسم والبريد وكلمة مرور من 12 حرفًا على الأقل');return}this.creating.set(true);this.http.post(`${environment.apiUrl}/administrators`,{fullName:this.fullName,email:this.email,password:this.password}).subscribe({next:()=>{this.fullName='';this.email='';this.password='';this.creating.set(false);this.notify.success('تم إنشاء المشرف');this.load()},error:e=>{this.creating.set(false);this.notify.error(errMsg(e))}})}toggle(row:any){this.http.patch(`${environment.apiUrl}/administrators/${row.id}/status`,!row.isActive).subscribe({next:()=>this.load(),error:e=>this.notify.error(errMsg(e))})}}
